// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { HorizontalBox, VerticalBox, StandardTableView, GroupBox} from "std-widgets.slint";
//import { GallerySettings } from "../gallery_settings.slint";
import { Page } from "page.slint";

export component BusInfoPage inherits Page {
    title: ("LoggingView");
    show-enable-switch: false;
    description: ("StandardTableView can be used to display a list of text elements in columns and rows. It can be imported from \"std-widgets.slint\"");
}
