// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { HorizontalBox, VerticalBox, StandardTableView, GroupBox} from "std-widgets.slint";
//import { GallerySettings } from "../gallery_settings.slint";
import { Page } from "page.slint";

export global LiveViewPageAdapter  {
    in property <[[StandardListViewItem]]> table_data;
    in property <string> test: "default";

    callback sort_ascending(int);
    callback sort_descending(int);
}

export component LiveViewPage inherits Page {
    in property <[[StandardListViewItem]]> fuckyou;
    title: ("Live CAN Messages");
    description: ("This page shows live traffic on the CAN Bus");

    Text {
        font-size: 14px;
        horizontal-alignment: center;
        text: LiveViewPageAdapter.test;

    }
    HorizontalBox {
        vertical-stretch: 1;
        // Title
        GroupBox {
            vertical-stretch: 0;

            StandardTableView {

                sort-ascending(index) => {
                    LiveViewPageAdapter.sort_ascending(index);
                }

                sort-descending(index) => {
                    LiveViewPageAdapter.sort-descending(index);
                }

                columns: [
                    { title: ("CAN ID")},
                    { title: ("Byte 1") },
                    { title: ("Byte 2") },
                    { title: ("Byte 3") },
                    { title: ("Byte 4") },
                    { title: ("Byte 5") },
                    { title: ("Byte 6") },
                    { title: ("Byte 7") },
                    { title: ("Byte 8") },
                    { title: ("TimeStamp") },
                    { title: ("Count") },
                ];
                rows: fuckyou;
            }
        }
    }
}
