// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Switch, GridBox, ListView, ScrollView, VerticalBox } from "std-widgets.slint";

//import { GallerySettings } from "../gallery_settings.slint";

export component Page inherits VerticalBox {
    in property<string> title: "title";
    in property<string> description: "description";
    in property<bool> show-enable-switch: true;

    preferred-width: 1020px;
    preferred-height: 800px;

    HorizontalLayout {
        Text {
            font-size: 20px;
            text <=> root.title;
        }

        // Spacer
        Rectangle {}

//        if show-enable-switch: Switch {
//            horizontal-stretch: 0;
//            text: ("Widgets enabled");
//            checked <=> GallerySettings.widgets-enabled;
//            enabled: true;
//        }
    }

    @children
}