export component CAN-Frame {
    in-out property <string> can_id;
    in-out property <string> byte_1_data;
    in-out property <string> byte_3_data;
    in-out property <string> byte_4_data;
    in-out property <string> byte_2_data;
    in-out property <string> byte_5_data;
    in-out property <string> byte_6_data;
    in-out property <string> byte_7_data;
    in-out property <string> byte_8_data;
    in-out property <duration> timestamp;
    in-out property <int> count;
}