import { Button, VerticalBox } from "std-widgets.slint";
import { LiveViewPage } from "pages/pages.slint";
import { SideBar } from "side_bar.slint";

export component AppWindow inherits Window {
    preferred-width: 700px;
    preferred-height: 500px;
    title: "RustyCANdapter";

    in-out property<int> counter: 42;
    callback request-increase-value();

    HorizontalLayout {
        side-bar := SideBar {
            title: "CANdapter";
            model: ["Live View", "Scheduled Frames", "Bus Info", "Settings", "About"];
        }

        if(side-bar.current-item == 0) : LiveViewPage {}
//        if(side-bar.current-item == 0) : ControlsPage {}
//        if(side-bar.current-item == 2) : TableViewPage {}
//        if(side-bar.current-item == 3) : TextEditPage {}
//        if(side-bar.current-item == 4) : EasingsPage {}
        if(side-bar.current-item == 5) :
        VerticalBox {
            Text {
                text: "Counter: \{root.counter}";
            }
            Button {
                text: "Increase value";
                clicked => {
                    root.request-increase-value();
                }
            }
        }
    }
}
