import { Button, VerticalBox } from "std-widgets.slint";
import { LiveViewPage, ScheduledFramesPage, LoggingPage, BusInfoPage, SettingsPage } from "pages/pages.slint";
import { SideBar } from "side_bar.slint";

export component AppWindow inherits Window {
    in property <[string]> serial-ports;
    preferred-width: 1200px;
    preferred-height: 800px;
    title: "RustyCANdapter";

    in-out property<int> counter: 42;
    callback request-increase-value();

    HorizontalLayout {
        side-bar := SideBar {
            title: "RustyCANdapter";
            model: ["Live View", "Scheduled Frames", "Logging", "Bus Info", "Settings"];
            width: 0.15 * parent.width;
            port-select: root.serial_ports;
        }

        if(side-bar.current-item == 0) : LiveViewPage {}
        if(side-bar.current-item == 1) : ScheduledFramesPage {}
        if(side-bar.current-item == 2) : LoggingPage {}
        if(side-bar.current-item == 3) : BusInfoPage {}
        if(side-bar.current-item == 4) : SettingsPage {}
    }
}
